### PR TITLE
pt-Br translation

### PR DESCRIPTION
**Pull request by KomashiFX**
`Not yet finished` some names in Portuguese have no translation and some are quite complicated, so I still need to check them before sending them all at once, **but the most important ones are already translated here**.

sorry for the bad English *(or good?)*, I used **DeepL** to try to make it easier for everyone.

### CODE REVIEW

**Comment by KomashiFX** [comment]
`note:` I don't know how well this *pull request* function works, I hope I sent everything correctly

**Comment by n1tr0-5urf3r** [comment]
> `note:` I don't know how well this _pull request_ function works, I hope I sent everything correctly

It's fine, I will have to make some adjustements to add `pt-br` as a supported languange.

As the localization is compiled into the .exe, I will have to build and release a new version for this. I will leave this pull request open until you are done with your translations. Some translations, mostly of fractal bosses, aren't even added yet in the template, I will add them soon. Just push your updates to your repository, they will be added to this pull request automatically. 

I will then push out a new build with some minor bug fixes and the updated translations later. 
Thank you for contributing! :)

**Comment by KomashiFX** [comment]
understood, when I finish everything I will send here. 

- some things are hindering this translation process but I promise I'll send it as soon as possible
**Maybe even today.**

**Comment by KomashiFX** [comment]
now its finished.

**Pull request merged**
