### PR TITLE
Update base.po

### PR DESCRIPTION
**Pull request by KomashiFX**
correcting exchanged translations

### CODE REVIEW

**Comment by n1tr0-5urf3r** [comment]
I had "mounted on ..." In the english case initially too, but it turned out to cut off too much other relevant info. It looked like "mounted on skysc..." in the status then. Im not sure If this ist what you want.

**Comment by KomashiFX** [comment]
Here show this

> name [TDA]
> in Jackal atThe Silve...
unknown png


> name [TDA]
> Mounted onThe Silverwastes
unknown2

**Comment by n1tr0-5urf3r** [comment]
Ooh so the problem is that it shows montado (mounted?) too if you are not mounted?

**Comment by KomashiFX** [comment]
I can't explain why it's all messed up in Rich Presence, and in the second image says I'm mounted in one place, I've really lost every q.i trying to form something that makes sense of what I'm saying.

**Comment by n1tr0-5urf3r** [comment]
Ok I think I understand now. Seems like this is a grammar issue and "on" and "in" are not directly translatable in this context. As English:"in <map>" is "no <map>" if you are on a mount and "en <map>" if you are not on a mount? 
Would "em raptor em The Silverwaste" be a grammarly correct expression?

**Comment by KomashiFX** [comment]
that's right

**Comment by n1tr0-5urf3r** [comment]
> that's right

Would "em raptor em The Silverwaste" then be okay as translation? If yes push it to the pull request and I will merge it :) Also note that 4 more strings to translate got added

**Comment by KomashiFX** [comment]
unfortunately I wouldn't correct it yet, I think it's better to leave this part in English for now

About the 4 new strings I will translate them right now

**Pull request closed without merging**
